### ISSUE TITLE
Bug at your installation instruction

### ISSUE THREAD

**Issue by thisavoropaev** [BGundlach/css3Fonts#2]
If install your app like you write, we have some problems since this line.
`ln -sT css3FontConverter/css3fonts ~/bin/css3fonts`

We don't have directory  `css3FontConverter` after the commands higher  and what is option `ln -sT`?

Please check your installation instructions again.

**Comment by BGundlach** [comment]
Shoot, the directory should be css3fonts and ln is the link command. -s is for symbolic link, -T specifies css3fontconverter/css3fonts (should be css3fonts/css3fonts) as the target for the link and ~/bin/css3fonts is the link name (where we're putting the shortcut)
